version: '2'
services:
  devoxx2019-app:
    image: devoxx2019
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://devoxx2019-mysql:3306/devoxx2019?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  devoxx2019-mysql:
    extends:
      file: mysql.yml
      service: devoxx2019-mysql
